from pathlib import Path

from moo_conformance.toast_semantic_matrix_generator import (
    EXPECTED_ROW_COUNT,
    REPO_ROOT,
    build_outputs,
)

EXPECTED_OUTPUTS = {
    "src/moo_conformance/_tests/builtins/toast_string_search_offset_matrix.yaml",
    "src/moo_conformance/_tests/language/toast_equality_matrix.yaml",
    "src/moo_conformance/_tests/language/toast_membership_matrix.yaml",
    "src/moo_conformance/_tests/language/toast_relational_matrix.yaml",
}


def test_generator_builds_the_complete_deterministic_matrix_set() -> None:
    outputs, counts = build_outputs()

    assert sum(counts.values()) == EXPECTED_ROW_COUNT == 1122
    assert {_relative(path) for path in outputs} == EXPECTED_OUTPUTS
    assert all(
        content.startswith(
            "# Generated by python -m "
            "moo_conformance.toast_semantic_matrix_generator; DO NOT EDIT BY HAND."
        )
        for content in outputs.values()
    )


def _relative(path: Path) -> str:
    return path.relative_to(REPO_ROOT).as_posix()
